In [1]:
import pandas as pd

In [3]:
df_chunks = pd.read_json('..\data\processed\chunks_simple.json')

In [5]:
df_chunks.head(1)

,chunk_text,question,answer,source_id,source_url,chunk_index,total_chunks,chunk_type,answer_date,read_count,average_rate,rate_count,question_len,answer_len,combined_len,chunked_at
0,Sual: Hüquqi şəxsin fəaliyyəti 10 ildir dayand...,Hüquqi şəxsin fəaliyyəti 10 ildir dayandırılmı...,"Bildiririk ki, hüquqi şəxsin ləğv edilməsi pro...",10826,https://www.taxes.gov.az/az/page/suallar-ve-ca...,0,1,simple,2026-04-23,62,0,0,374,278,652,2026-05-11 11:15:11.949612+00:00

In [7]:
df_chunks.chunk_text[0]

'Sual: Hüquqi şəxsin fəaliyyəti 10 ildir dayandırılmışdır. Təsisçisi Azərbaycan Respublikasının vətəndaşı olan bir nəfərdir. Hüquqi şəxsin debitor və kreditor borcları, o cümlədən vergilər və digər məcburi ödənişlər üzrə heç bir borcu yoxdur.\r\nXahiş edirəm, qeyd olunan hüquqi şəxsin dövlət qeydiyyatından çıxarılması və VÖEN-in ləğv edilməsi prosedurları barədə məlumat verəsiniz.\nCavab: Bildiririk ki, hüquqi şəxsin ləğv edilməsi proseduru, o cümlədən təqdim olunmalı sənədlərin siyahısı və sənədlərin təqdim edildiyi vergi orqanı barədə ətraflı məlumatla buradan tanış ola bilərsiniz:\xa0https://www.taxes.gov.az/az/page/huquqi-sexsin-legv-edilmesi-proseduru-haqqinda'

In [15]:
df_chunks[~(df_chunks['chunk_type'] == 'simple')]

Empty DataFrame
Columns: [chunk_text, question, answer, source_id, source_url, chunk_index, total_chunks, chunk_type, answer_date, read_count, average_rate, rate_count, question_len, answer_len, combined_len, chunked_at]
Index: []